### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by thomas-louvigne**
it is not complete at 100%, but it's translated in most of case.

### CODE REVIEW

**Comment by thomas-louvigne** [comment]
I got problem for some traductions, because the french syntax don't works like in english.  

- years: =>" Années "
- days => " Jours "
- hours => " Heures "
- mins => " Minutes "

The "ago" word don't exist in french 

`it was publish 1 Month Ago` , in french should be traduct by ` Cela à été publié il y a 1 mois"

**Ago** can be translated by *il y a* XX **mois**  (Mois <-> month)

**Comment by elkan1788** [comment]
@thomas-louvigne Thanks for your PR , but the main branch only use to release action, so can you move the change into develop branch , Thanks.

**Comment by thomas-louvigne** [comment]
I have just update the language, i have test it, it's works enough, you can merge it.

**Comment by elkan1788** [comment]
@thomas-louvigne Thanks for your response, but we need defined the development rules and we always to under this, so hope you can follow it.

**Comment by thomas-louvigne** [comment]
yes, i thinks it ok now

**Comment by elkan1788** [comment]
> yes, i thinks it ok now

Thanks for your contributed.

**Pull request merged**
